### ISSUE TITLE
Am I tired or is there no AppImages or instructions for AppImages in this repo?

### ISSUE THREAD

**Issue by AmyMoriyama** [eyedeekay/I2P-Snaps-and-Appimages#1]
As title says. I like the idea of AppImages, but, they have their difficulties and limitations.

**Comment by eyedeekay** [comment]
There was before, it was generated from the snap by a crude conversion process. There is again, but this time it uses the proper AppDir setup, which is set up in the appimage.sh script. Both the snap and the appimage, which have been broken since about the time of this issue's filing, have been fixed.
